version: '3.9'
services:
  web:
    build: .
    image: spi-web:prod
    container_name: spi-web
    command: ["/entrypoint.prod.sh"]
    env_file:
      - .env
    environment:
      - DEBUG=0
    depends_on:
      - db
    volumes:
      - media:/app/media
      - staticfiles:/app/staticfiles

  nginx:
    image: nginx:alpine
    container_name: spi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/app/media:ro
      - staticfiles:/app/staticfiles:ro
    depends_on:
      - web

  db:
    image: postgres:15-alpine
    container_name: spi-db
    environment:
      - POSTGRES_DB=spi
      - POSTGRES_USER=spi
      - POSTGRES_PASSWORD=spi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  media:
  staticfiles:
