version: '3.9'
services:
  web:
    build: .
    image: spi-web:latest
    container_name: spi-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media:/app/media
      - staticfiles:/app/staticfiles
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,http://localhost:8000
    restart: unless-stopped
volumes:
  media:
  staticfiles:
